### ISSUE TITLE
I have a CSV file that's like 500k lines long and it's seriously slowing down the engine

### ISSUE THREAD

**Issue by ghost** [timothyqiu/godot-csv-data-importer#3] opened 2023-09-19 19:27 UTC
IDK if this is because the plugin isn't optimized or I should use a smaller CSV file.

**Comment by timothyqiu** [comment] 2023-09-21 03:25
How long does it take to reimport your CSV file? I tested with a 500k line CSV with randomly generated content. It takes about 3~4 seconds to import. This is less than one second longer than iterating CSV manually with `FileAccess`.

Further optimizations would require something like GDExtension. But I think that'll be an overkill. This import process only happen in the editor, and when something is changed in the CSV file.

**Comment by ghost** [comment] 2023-09-22 15:39
It's not how long it takes to import, it's actually lagging the editor when I try to write code. When I removed the file the lag went away.

**Comment by timothyqiu** [comment] 2023-09-22 16:34
Thank you for the information. I think I can reproduce the stuttering now.

When I type `preload()` and autocomplete the path to that large CSV file, the editor stutters when I hit enter to accept the autocomplete option. And it also sutters a second time a few seconds later.

But I think it's caused by the nature of GDScript's `preload()` as the loading (of that large amount of data) happens when loading / analyzing the script. Changing `preload()` to `load()` won't stutter the editor.

An import plugin is run during the import process, i.e., only when you press the "Reimport" button or when the editor detects something changed in the source file (the raw `.csv` file in this case). The imported CSV file is a plain old resource file with no executable code. So the editor should just be busy loading the large amount of data.

**Comment by timothyqiu** [comment] 2024-07-15 09:11
Closing as explained above. This is not related to plugins. `preload()`ing any large resource file will cause similar editor stuttering.

I think it's better to split the large CSV into smaller ones.

If you find any errors in my analysis, or encounter any other situations causing this stuttering, please feel free to reopen this issue or submit a new issue :)

**Closed as completed by timothyqiu** 2024-07-15 09:11 UTC
Labels: wontfix
